package:
  name: torch_trainer
  version: "1.0"

source:
  git_url: git@github.com:francescocastelli/torch-trainer.git

requirements:
  build:
    - python

  run:
    - python

about:
  home: git@github.com:francescocastelli/torch-trainer.git
