package:
  name: torchtrainer
  version: "1.1"

source:
  path: ../

build:
  number: 1

test:
  requires:
    - python

requirements:
  host:
    - python

  run:
    - python

about:
  home: git@github.com:francescocastelli/torch-trainer.git
